[tool.poetry]
name = "ffda-oob-state-collector"
version = "0.1.0"
description = ""
authors = ["David Bauer <mail@david-bauer.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
